<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d7d8ad9e-38b8-486a-990f-02aea53e54b5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexora.Identity.Application\Nexora.Identity.Application.csproj" />
    <ProjectReference Include="..\Nexora.Identity.Infrastructure\Nexora.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
